### ISSUE TITLE
Nuget package target framework 

### ISSUE THREAD

**Issue by NeilC** [Microsoft/Yams#23]
While trying to install Yams through nuget to a new worker role I'm getting the following message.

`Could not install package 'Etg.Yams 1.0.13'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author`

My project was initially targeting .net 4.5.1 but I lowered it when I got that error for the first time. Does it not support these versions or is something wrong with the package perhaps?

Edit -- 
Looks like it installs fine on framework 4.6.1.

**Comment by nehmebilal** [comment]
Hi @NeilC, thanks for reporting!

Yes, by default NuGet will make the target project the same as the project its being built from (when using `nuget pack Etg.Yams.csproj`).

Can you simply change the worker role target to 4.6.1 or is there a reason why you need to keep 4.5?

**Comment by NeilC** [comment]
I did go that route but came across an impassable warning saying that Cloud Service projects must target v4 or v4.5. I ended up building yams from source and re-targeting it to 4.5, its appears to be running normally in my test cloud service for the last 30 minutes. 

Oh also it's probably worth mentioning to add the "LocalStoreDirectory" setting in the "Local Storage" configuration section of the cloud service project, not having this threw an unhelpful aggregate exception for me.

**Comment by nehmebilal** [comment]
> I did go that route but came across an impassable warning saying that Cloud Service projects must target v4 or v4.5. I ended up building yams from source and re-targeting it to 4.5, its appears to be running normally in my test cloud service for the last 30 minutes.

I've seen that same warning but deployed Yams anyway with 4.6.1 in a cloud service and it's working as expected. How is the warning impassable?

> Oh also it's probably worth mentioning in the docs to add the "LocalStoreDirectory" setting in the "Local Storage" configuration section of the cloud service project, not having this threw an unhelpful aggregate exception for me.

PR? :smile:

**Comment by NeilC** [comment]
I'm not sure why it wouldn't compile then, perhaps I had VS set to break on warnings now that I think about it. I'll try it all out again on 4.6.1 tomorrow and send PR for docs :+1:

**Comment by nehmebilal** [comment]
Sounds good, thanks!

**Comment by nehmebilal** [comment]
Any updates?

**Comment by nehmebilal** [comment]
Doesn't seem to be an issue, closing...

**Comment by jdom** [comment]
Just noticed this too. It does publish with a warning to Cloud Services. Nevertheless, it actually runs on .NET 4.5.1. You can verify this by adding some code that is only supported in .NET 4.6 (like AsyncLocal<T>) and you'll see that the role recycles.
So if Yams doesn't *really* require 4.6 to run, maybe it's worth lowering the framework requirement to 4.5.1 and avoid the incorrect notion that code that targets .NET 4.6.1 will actually work. Alternatively the Yams host could have a startup task to update the framework to the latest version.

**Comment by nehmebilal** [comment]
Good observation!

Sounds like we should at least lower the cloud service samples to 4.5.1. Yams (the library) is not tied to cloud services and thus supports 4.6. Does that make sense?

**Comment by jdom** [comment]
Hmmm, it supports 4.6, but does it require it? Because the library should target the minimum framework (or at least 4.5.1 if we want to avoid the Cloud Services issue only) that it can, but that doesn't mean it couldn't be used in .NET 4.6 if someone wants to.
Also, from what I understand, Yams would just start a process with the executable file you point it to, and does not care what's the target framework of that process (or even whether it's a .NET app). Am I correct?
If so, my recommendation is to have the library target 4.5.1, and also have the cloud sample target that (since the sample is just used to start other processes).
As an addition (but not as an alternative) we *might* want to have the sample install the latest .NET Framework as a startup task, in case the target process requires it. But that's just a nice to have sample code.

**Comment by jdom** [comment]
BTW, as an extra note, we *will not* be able to have the library keep targeting 4.6 and have the sample project target 4.5.1, because it will not be able to add the reference to library.

**Comment by nehmebilal** [comment]
The advantage of targeting 4.6 in the library is to be able to use the features of that version in Yams development. 

If I'm not wrong, the NuGet package can target both 4.5 and 4.6 even if the library is built with 4.6 as long as the Api is compatible? But if 4.6 is not installed at all, that might not work.

**Comment by jdom** [comment]
No, if you want it usable by both net 4.5 and net 4.6, you need to compile with 4.5.
Are you actually using any feature from 4.6 that is not available in 4.5?

**Comment by nehmebilal** [comment]
Probably not but I'm sure there are many performance and security fixes in 4.6 over 4.5. I agree with you that if we want to officially support 4.5 we need to provide a compatible dll but it feels like the issue is more about cloud services being behind. The ideal solution would be to compile Yams for both and provide both dlls.

**Comment by jdom** [comment]
The thing is that it's up to the user to host it in Net 4.5 or 4.6. If he uses the 4.6 runtime, then it doesn't matter that the assembly was originally built for 4.5, it will get all of the perf improvements anyway (security is patched for both frameworks individually, so in that case there's no advantage of using 4.6). This is of course true unless you are actually using a new api that is not even available on 4.5, which seems it's not the case,  otherwise you won't be able to multistage either. 
Also, I would doubt that Yams has any hot path that would benefit of a completely high performance api that is not available in 4.5. 
After all it's probably the target app the one that will be doing a lot of work and be cpu intensive, not yams itself

**Comment by nehmebilal** [comment]
Thanks for the into @jdom. Based on the above facts and since Yams is most likely not using any 4.6 only Apis, changing the target framework to 4.5 sounds reasonable to me.

**Comment by nehmebilal** [comment]
Resolved by #24

**Comment by nehmebilal** [comment]
Actually, I'll keep this open until the sample is updated. @jdom are you taking care of that? :)

**Comment by nehmebilal** [comment]
Resolved by #24 and #25
