### ISSUE TITLE
Tutorial for on premise needs the cloud?

### ISSUE THREAD

**Issue by Razzeee** [Microsoft/Yams#38]
The tutorials read, like I can run it on premise, but need a azure storage anyway?

See: https://github.com/Microsoft/Yams/blob/master/Samples/Etg.Yams.ARM/README.md 

> - storageAccount: Azure Storage account name
> - storageKey: Azure Storage account key

**Comment by nehmebilal** [comment]
The tutorial is not specific to on-premises or Azure. It just describes how to deploy Yams on a regular VM (non cloud service).

To deploy Yams on premises (or in Azure), you need a storage for you binaries that all your machines can access. This can be done by creating a corresponding implementation of `IDeploymentRepository`. We currently have one compatible with blob storage, which is why you still need blob storage even on premises.

I believe that several people have created deployment repository based on different technologies but unfortunately those have not been contributed back to Yams.

**Comment by Razzeee** [comment]
Thanks for getting back. So blob storage is something from the azure world?

So the this is purely theoretically at the moment?
> Depending on what kind of storage provider is being used, these could be folders in a blob- or file-system-based deployment storage provider, columns in a relational database table, etc.

https://github.com/Microsoft/Yams/blob/master/Docs/Overview.md

**Comment by nehmebilal** [comment]
> Thanks for getting back. So blob storage is something from the azure world?
Yes, blob storage is an Azure technology but in from Yams perspective it's just a no sql database that is used to store blobs.

> So the this is purely theoretically at the moment?
> Depending on what kind of storage provider is being used, these could be folders in a blob- or file-system-based deployment storage provider, columns in a relational database table, etc.

I wouldn't say theoretical, there is a file-system based implementation of `IDeploymentRepository` used in the end-to-end tests and it works fine. That demonstrates that Yams is decoupled from specific technologies used to implement the `IDeploymentRepository`. However, the file-system based repository is limited to one machine and in real-world, there should be one storage shared among multiple machines. If you have a remotely accessible file-system on your network, you can probably use the file-system based deployment repository but I haven't tried that.

Also @danvanderboom has implemented a SQL based deployment repository and I believe it worked well for him.

**Comment by nehmebilal** [comment]
Hi @Razzeee. I'm just wondering if I answered your question?

**Comment by Razzeee** [comment]
Yes, if we go forward with yams I will probably just implement `IDeploymentRepository` then. Thank you.
