### ISSUE TITLE
Yams Client - confusion with arguments

### ISSUE THREAD

**Issue by h3ko** [Microsoft/Yams#46]
Hello,

We ran into some problems with Yams Client arguments/options (pipe names). In addition to _--ExitPipeName_ we also use some other options and arguments. If we pass all arguments into the YamsClientFactory app shuts down (`Parser.Default.ParseArgumentsStrict(config.ProcessArgs, options)` fails ==> and `Environment.Exit(DefaultExitCodeFail)` kills the app).

It is unclear how the argument parser works - which argument is which pipe, and/or option names are skipped/mapped to proper argument values.

As arguments are not very clear and straightforward, explicit properties in the newer versions for pipe names would probably be better?

Maybe something like
`IYamsClient CreateYamsClient(string initializationPipeName, string exitPipeName, string healthPipeName, YamsClientConfig yamsClientConfig); `
 
Very cool framework tho, we use it in production ;)

Kind regards,
Heko

**Comment by nehmebilal** [comment]
Hi @h3ko,

Thanks for reporting this issue.

We can't expose the pipe names in `CreateYamsClient` because pipe names are implementation specific. If we decide to switch the IPC tech to something else, that shouldn't affect the public Api.

I'll look into the issue / add a unit test to make sure it doesn't fail when there are extra options/arguments.

Thanks!

**Comment by nehmebilal** [comment]
Just opened #47 to resolve this. 

I agree that `YamsClientConfig.ProcessArgs` is a bit confusing. For example, "Foo --InitializationPipeName abc123" should be passed as {"Foo, "--InitializationPipeName", "abc123"} and not {"Foo, "--InitializationPipeName abc123"} (take a look at the tests in the PR). It's consistent with the way that the `Main()` function receives arguments so that they can be passed along.

We can switch `YamsClientConfig.ProcessArgs` to be a string but then the app will have to join the args received in Main() and pass it along.

**Comment by nehmebilal** [comment]
The crash should not happen again with additional args as shown in the tests. Will close this for now. Please let me know if you have any other concerns. I will deploy this fix as part of the next stable release (soon).

**Comment by h3ko** [comment]
Thank you! I'll try it as soon as I can (y)

Kind regards,
h3k0
